USE [master]
GO

/****** Object:  Database [DB_Sewing_Factory]    Script Date: 22.05.2020 13:04:35 ******/
CREATE DATABASE [DB_Sewing_Factory]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'DB_Sewing_Factory', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL12.FIERY\MSSQL\DATA\DB_Sewing_Factory.mdf' , SIZE = 5120KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'DB_Sewing_Factory_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL12.FIERY\MSSQL\DATA\DB_Sewing_Factory_log.ldf' , SIZE = 2048KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO

ALTER DATABASE [DB_Sewing_Factory] SET COMPATIBILITY_LEVEL = 120
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [DB_Sewing_Factory].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [DB_Sewing_Factory] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [DB_Sewing_Factory] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [DB_Sewing_Factory] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [DB_Sewing_Factory] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [DB_Sewing_Factory] SET ARITHABORT OFF 
GO

ALTER DATABASE [DB_Sewing_Factory] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [DB_Sewing_Factory] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [DB_Sewing_Factory] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [DB_Sewing_Factory] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [DB_Sewing_Factory] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [DB_Sewing_Factory] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [DB_Sewing_Factory] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [DB_Sewing_Factory] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [DB_Sewing_Factory] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [DB_Sewing_Factory] SET  DISABLE_BROKER 
GO

ALTER DATABASE [DB_Sewing_Factory] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [DB_Sewing_Factory] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [DB_Sewing_Factory] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [DB_Sewing_Factory] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [DB_Sewing_Factory] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [DB_Sewing_Factory] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [DB_Sewing_Factory] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [DB_Sewing_Factory] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [DB_Sewing_Factory] SET  MULTI_USER 
GO

ALTER DATABASE [DB_Sewing_Factory] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [DB_Sewing_Factory] SET DB_CHAINING OFF 
GO

ALTER DATABASE [DB_Sewing_Factory] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [DB_Sewing_Factory] SET TARGET_RECOVERY_TIME = 0 SECONDS 
GO

ALTER DATABASE [DB_Sewing_Factory] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [DB_Sewing_Factory] SET  READ_WRITE 
GO

